---
abstract: 'Numbers with error propagation and scientific rounding'
author:
  - 'Steffen Mueller <smueller@cpan.org>, L<http://steffen-mueller.net/>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::LectroTest: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-WithError
no_index:
  directory:
    - inc
    - t
requires:
  Math::BigFloat: 1.40
  Params::Util: 0.10
  perl: 5.6.0
  prefork: 1.00
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
